### ISSUE TITLE
Hello, I will report an error when using Raidforum.py

### ISSUE THREAD

**Issue by h35h4n9** [VikShiv/Dark_Web_Scraping#1]
Hello, I will report an error when using Raidforum.py
```
Traceback (most recent call last):
  File "raidForums.py", line 12, in <module>
    from ..items import RaidforumsItem, ReplyItems
ValueError: attempted relative import beyond top-level package
```
Looking forward to your reply

**Comment by VikNim** [comment]
Here is my items.py:

class ReplyItems(Item):
	reply_content = Field()
	reply_timestamp = Field()
	reply_media_links = Field()
	reply_general_links = Field()
	reply_author = Field()
	reply_author_membership = Field()


class RaidforumsItem(Item):
	thread_url = Field()
	thread_timestamp = Field()
	thread_reply_no = Field()
	thread_content = Field()
	thread_media_links = Field()
	thread_general_links = Field()
	thread_group = Field()
	thread_replies = Field()

	author_name = Field()
	author_age = Field()
	author_membership_level = Field()
	author_joined_date = Field()
	author_location = Field()
	author_posts_count = Field()
	scraped_date = Field()
