### ISSUE TITLE
cannot run program, missing packages

### ISSUE THREAD

**Issue by ghost** [VikShiv/Dark_Web_Scraping#3]
Hi,

Hope you are all well !

I tried to run some scripts and it seems that some packages are missing.

```bash
Traceback (most recent call last):
  File "bestBlackHatSpider.py", line 12, in <module>
    from ..items import BestblackhatforumItem, ReplyItems
ValueError: Attempted relative import in non-package
```

Is it possible to fix it ?

Cheers,
X

**Comment by VikNim** [comment]
Hi,
The error is regarding the items.py file. Go to your items.py file and check what is the class name defined there. BestBlackhatforumItems and ReplyItems are the classes I had defined for my work.
When we create project using scrapy command few files are generated automatically along with project i.e items.py pipeline.py and few others.
