### ISSUE TITLE
How are you bypassing raid recaptcha?

### ISSUE THREAD

**Issue by blueteamzone** [VikShiv/Dark_Web_Scraping#4]
Hey, I was wondering how are you bypassing RF's recaptcha!
Thanks.

**Comment by VikNim** [comment]
Hello blueteamzone,
 I used to login into the website ever day and I would record the request and response of website from console, then while scraping passing the same response to website which creates illusion that same user is logging in. response contains the username, password, CloudFlareToken etc.
This way there would not be image captcha, however there might be new techniques in market to bypass the that captcha as well. 
Or you can automate this process as well using Selenium or PyAutoGUI. Open a website, login into it and record a request and response objects also a cloudflare token logout and close the browser. Then pass this all to scrapy program and start scraping :)
