### ISSUE TITLE
where is this module

### ISSUE THREAD

**Issue by jhasaurabh571** [VikShiv/Dark_Web_Scraping#5]
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\Saurabh\osint\dark web\Dark_Web_Scraping-master\bestBlackHatSpider.py", line 12, in <module>
    from ..items import BestblackhatforumItem, ReplyItems
ImportError: attempted relative import with no known parent package

**Comment by VikNim** [comment]
Hi, 
When you create a scrapy project, each scraper gets it own items.py to import it from. You basically can define which data-fields you want to scrape from website and put them into this items.py. So this items.py, you would have to define in your project. See here for docs: [https://docs.scrapy.org/en/latest/topics/items.html](https://docs.scrapy.org/en/latest/topics/items.html)
